#pragma once

#define ONE_WIRE_BUS 23

#define FLOW_SWITCH_PIN 34
#define HIGH_PRESSURE_SWITCH_PIN 35
#define LOW_PRESSURE_SWITCH_PIN 32
#define WATER_PUMP_DM_PROTECTION_PIN 33
#define MAIN_ON_OFF_SWITCH_PIN 25

#define COMPRESSOR1_PIN 26
#define COMPRESSOR2_PIN 27
#define COMPRESSOR3_PIN 14
#define COMPRESSOR4_PIN 12

#define WEB_PORTAL_PIN 39
#define RESET_WIFI_SETTINGS_PIN 0

#define WATER_PUMP_PIN 13

#define ENCODER_CLK_PIN 4
#define ENCODER_DT_PIN 2
#define ENCODER_SW_PIN 16

#define BUZZER_PIN 15
#define BUZZER_FREQUENCY_HZ 2000
#define BUZZER_BUZZ_DELAY_MS 100

//#define FLOW_SWITCH_PIN_ACTIVE_STATE LOW
//#define WATER_PUMP_DM_PROTECTION_PIN_ACTIVE_STATE LOW

//#define HIGH_PRESSURE_SWITCH_PIN_ACTIVE_STATE HIGH
//#define LOW_PRESSURE_SWITCH_PIN_ACTIVE_STATE HIGH

//#define MAIN_ON_OFF_SWITCH_PIN_ACTIVE_STATE LOW

//#define WEB_PORTAL_PIN_ACTIVE_STATE LOW
//#define RESET_WIFI_SETTINGS_PIN_ACTIVE_STATE LOW